"""adds caretaker_id foreign key to Cat model

Revision ID: db0a605e7a78
Revises: ace89ea08a68
Create Date: 2025-05-06 13:25:23.092320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db0a605e7a78'
down_revision = 'ace89ea08a68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cat', schema=None) as batch_op:
        batch_op.add_column(sa.Column('caretaker_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'caretaker', ['caretaker_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cat', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('caretaker_id')

    # ### end Alembic commands ###
